In [1]:
import torch 
import torchvision 
import numpy as np 
import torch.nn as nn
import torchvision.transforms as transforms

### Basic Autograd Example 1

In [2]:
temp = torch.FloatTensor([23, 43, 26 , 29 , 37 , 23.0])
temp.size()

torch.Size([6])

In [3]:

#zero dim tensor or just a scaler value
tensor_0d = torch.tensor(1)
print(1)

tensor_1d = torch.tensor([2, 3, 4, 5, 6])
print("1D tensor (Vector):")
print(tensor_1d)
print()

tensor_2d = torch.tensor([[1, 2] , [3, 4]])
print("2D tensor(matrix) :")
print(tensor_2d)
print()

random_tensor = torch.rand(2,3)
print(random_tensor)


zeros_tensor = torch.zeros(2,3)
print(zeros_tensor)

ones_tensor  = torch.ones(4,5)
print(ones_tensor)

row_tensor = torch.zeros(1 , 5)
print(row_tensor)

col_tensor  = torch.zeros(6 , 1)
print(col_tensor)


1
1D tensor (Vector):
tensor([2, 3, 4, 5, 6])

2D tensor(matrix) :
tensor([[1, 2],
        [3, 4]])

tensor([[0.4650, 0.2592, 0.3693],
        [0.5935, 0.2970, 0.6884]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])


### Tensor Operations in PyTorch

**Indexing:** Indexing lets you retrieve specific elements or smaller sections from a larger tensor. <br>
**Slicing:** Slicing allows you to take out a portion of the tensor by specifying a range of rows or columns.<br>
**Reshaping:** Reshaping changes the shape or dimensions of a tensor without changing its actual data. This means you can reorganize the tensor into a different size while keeping all the original values intact.

In [4]:
#indexing
tensor = torch.tensor([ [1,2] ,
                        [3,4] ,
                        [5, 6]
                        ])

element = tensor[1, 0]   #row 1 , column 0 
print(element)

#slicing

slice_tensor = tensor[:2 , :]
print(slice_tensor)

#reshaping
reshaped_tensor = tensor.view(6,1) 
print(reshaped_tensor)



tensor(3)
tensor([[1, 2],
        [3, 4]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


### Common Tensor Functions: Broadcasting, Matrix Multiplication, etc.
PyTorch offers a variety of common tensor functions that simplify complex operations.<br>

- **Broadcasting** allows for automatic expansion of dimensions to facilitate arithmetic operations on tensors of different shapes.
- **Matrix multiplication** enables efficient computations essential for neural network operations.

``Broadcasting Rule (PyTorch & NumPy):``
- Starting from the rightmost dimension, compare dimensions.
- Dimensions must either match or one of them must be 1.

In [ ]:
#broadcasting alter the order of the matrix to make the arithmatic operation possible 
#for example: A(3,3) and B(1,3). So you know addition is not possible
A =torch.tensor([[1, 2, 3 ],
     [4, 5, 6],
     [7, 8, 9]])
B =torch.tensor([[ 4, 5, 6]]) 


# But Broadcasting just repeat the row and alter the order  to make the addition possible B = [[4, 5, 6] , [4, 5, 6] ,[4, 5, 6]]
broadcasted_result = A + B #broadcasting is automatic in numpy , torch

print(broadcasted_result)


#broadcasting in multiplcation 
mA = A #mA is just the A matrix(3,3)
mB = torch.tensor([[1, 2, 3]])
#mB is a (1,3) matrix . So you know matrix multiplication is not possible traditionally(mA(3,3) X mB(2, 3)). But with broadcasting__
#as dimension of mB has one of the dimesion as 1 , so multiplication is possible with broadcasting 
Broadcasted_mResult = mA*mB 
print(Broadcasted_mResult)




#multiplication 
multiplicated_result = torch.matmul(mA, mB.T) #you have to transpose mB to make the multiplication possible
print(multiplicated_result)


tensor([[ 5,  7,  9],
        [ 8, 10, 12],
        [11, 13, 15]])
tensor([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]])
tensor([[14],
        [32],
        [50]])


### GPU Acceleration with PyTorch
By transferring tensors to the GPU, you can significantly reduce training times and improve performance.

In [22]:
#use in google collab for better understanding

import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using {device}")

tensor_size = (1000, 1000)
a = torch.randn(tensor_size , device = device) #random value but with normal distribution(mean = 0 , std = 1)
b = torch.randn(tensor_size , device = device) #random vlaue but with normal distribution(mean - 0 , std = 1)
c = a + b 
print("result shape(Moved to CPU for printing)" , c.cpu().shape) #GPU printing is slower

print("Current GPU memory Usage:")
print(f"Allocated:{torch.cuda.memory_allocated(device)/1024**2: .2f} MB") #from bytes to MB( byte to KB -> KB to MB - > 1024x1024)
print(f"Cached: {torch.cuda.memory_reserved(device)/1024**2 :.2f} MB")
torch.cuda.empty_cache()

Using cpu
result shape(Moved to CPU for printing) torch.Size([1000, 1000])
Current GPU memory Usage:
Allocated: 0.00 MB
Cached: 0.00 MB
